### ISSUE TITLE
Temperature at 4000 degrees

### ISSUE THREAD

**Issue by ignamartinoli** [catppuccin/btop#2]
Hi,
I see that `btop` always says that I am 4000 degrees

![screenshot_](https://user-images.githubusercontent.com/103866722/172032017-5f8d6f25-8e64-46bd-870b-c336bc1fc8e8.png)

which is false

```shell
sicro@sicro ~ $ cat /sys/class/thermal/thermal_zone0/temp
33000
```

**Comment by andreasgrafen** [comment]
Heya, sorry for the late reply. You probably want to post this on the [original BTOP repo](https://github.com/aristocratos/btop) is this one is only a colour scheme.

**Comment by ignamartinoli** [comment]
@andreasgrafen omg, sorry, it seems that I got confused by Firefox URL's autocompletion

**Comment by andreasgrafen** [comment]
@ignamartinoli absolutely no worries – happens to the best of us. c:
